# Site Build Settings

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title
future: true
plugins: [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

title: "POLYGRIM"
description: "BRIMMING"
author: "Polygrim"
url: "//polygrimmusic.com"
logo: "/assets/img/polygrim_logo_1.jpg"

include:
  - pages

hide_post_share: true
hide_related_posts: true
