google-ID: ''

menu:
- {name: 'MUSIC', url: 'music'}
- {name: 'EVENTS', url: 'events'}
- {name: 'DUSTYROOM', url: 'https://dustyroom.com'}
- {name: 'WHOAMI', url: 'whoami'}
- {name: 'CONTACT', url: 'contact'}

social:
- {icon: 'spotify', link: 'https://open.spotify.com/artist/018A6LxO13Q73gvr4VoY6f'}
- {icon: 'apple', link: 'https://music.apple.com/us/artist/polygrim/965253375'}
- {icon: 'bandcamp', link: 'https://polygrim.bandcamp.com/'}
- {icon: 'instagram', link: 'https://instagram.com/polygrim'}
- {icon: 'facebook', link: 'https://www.facebook.com/polygrim'}
- {icon: 'youtube', link:'https://www.youtube.com/channel/UC1HB44Xj4XLQHBqnYv7qkAA'}
- {icon: 'soundcloud', link: 'https://soundcloud.com/polygrim'}
- {icon: 'twitter', link: 'https://twitter.com/polygrim'}
- {icon: 'envelope', link: 'mailto:info@polygrimmusic.com'}

pagination:
  enabled: false

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
