google-ID: ''

menu:
- {name: 'MUSIC', url: 'music'}
- {name: 'EVENTS', url: 'events'}
- {name: 'DUSTYROOM', url: 'https://dustyroom.com'}
- {name: 'WHOAMI', url: 'whoami'}
- {name: 'CONTACT', url: 'contact'}

social:
- {icon: 'fa-spotify', link: 'https://open.spotify.com/artist/018A6LxO13Q73gvr4VoY6f'}
- {icon: 'fa-apple', link: 'https://music.apple.com/us/artist/polygrim/965253375'}
- {icon: 'fa-bandcamp', link: 'https://polygrim.bandcamp.com/'}
- {icon: 'fa-instagram', link: 'https://instagram.com/polygrim'}
- {icon: 'fa-facebook', link: 'https://www.facebook.com/polygrim'}
- {icon: 'fa-youtube', link:'https://www.youtube.com/channel/UC1HB44Xj4XLQHBqnYv7qkAA'}
- {icon: 'fa-soundcloud', link: 'https://soundcloud.com/polygrim'}
- {icon: 'fa-twitter', link: 'https://twitter.com/polygrim'}
- {icon: 'fa-envelope', link: 'mailto:info@polygrimmusic.com'}

pagination:
  enabled: false

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
