disqus:
  comments: false
  disqus_shortname: 'polygrim'

google-ID: ''

menu:
- {name: 'WHOAMI',              url: 'whoami'}
- {name: 'Contact',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link:    'https://twitter.com/polygrim'}
- {icon: 'facebook', link:   'https://www.facebook.com/polygrim'}
- {icon: 'instagram', link:  'https://instagram.com/polygrim'}
- {icon: 'envelope', link:   'mailto:info@polygrimmusic.com'}

pagination:
  enabled: false

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
